import os
import glob
import dotenv
import gc
from typing import TYPE_CHECKING

from astropy.io import fits
from astropy.wcs import WCS
from astropy.coordinates import SkyCoord
import astropy.units as u
import numpy as np
import pandas as pd
from tqdm import tqdm
from ..utils import pixel_2_arcmin_size, arcmin_2_pixel_size

if TYPE_CHECKING:
    from .mosaic import Mosaic


dotenv.load_dotenv()
PATH_TO_PACKAGE = os.getenv("PATH_TO_PACKAGE", "")
DR2_BASE_DIR = os.getenv("DR2_BASE_DIR", "/disks/paradata/shimwell/LoTSS-DR2/mosaics")
DR3_BASE_DIR = os.getenv("DR3_BASE_DIR", "/disks/paradata/shimwell/Beyond-DR2/mosaics/LoTSS-DR3-mosaics/")
RA0h_field = os.getenv("RA0h_field", "RA0h_field")
RA13h_field = os.getenv("RA13h_field", "RA13h_field")


def find_field_path(field_name: str, release: str) -> str:
    """
    Find the base path for the mosaic field.

    :param field_name: Name of the mosaic field
    :type field_name: str
    :param release: Data release ("DR2" or "DR3")
    :type release: str
    :return: Base path for the mosaic field
    :rtype: str
    """
    release = release.upper()
    if release == "DR2":
        # Get all subdirectories in DR2_BASE_DIR + the two field names
        search_paths = [
            os.path.join(DR2_BASE_DIR, RA0h_field),
            os.path.join(DR2_BASE_DIR, RA13h_field)
        ]
    elif release == "DR3":
        # All the DR3 mosaics are in the same directory so we can just
        # return the base path for DR3
        return DR3_BASE_DIR
    else:
        raise ValueError(f"Unsupported release: {release}, expected 'DR2' or 'DR3'.")

    for base_path in search_paths:
        subdirs = glob.glob(os.path.join(base_path, "*"))
        for subdir in subdirs:
            if os.path.basename(subdir) == field_name:
                return base_path
    raise FileNotFoundError(f"Field {field_name} not found in expected directories.")


def get_list_of_mosaics(mosaic_coverage_file: str = 'default', release: str = "DR2") -> list["Mosaic"]:
    """
    Get the list of Mosaic objects from the mosaic coverage CSV file. It assumes
    that the CSV file has columns: field_name, ra, dec, ra_min, ra_max, dec_min, dec_max, ra_size, dec_size.
    Usually this file is generated by running the `get_mosaic_coverage.sh` script in /scripts folder.
    
    :param mosaic_coverage_file: Path to the mosaic coverage CSV file
    :return: List of Mosaic objects
    """
    mosaic_coverage_file = _get_mosaic_coverage_filepath(mosaic_coverage_file, release)
    from .mosaic import Mosaic

    df = pd.read_csv(mosaic_coverage_file)

    mosaics = []
    for _, row in df.iterrows():
        mosaic = Mosaic(
            field_name=row['field_name'],
            ra=row['ra'],
            dec=row['dec'],
            ra_min=row['ra_min'],
            ra_max=row['ra_max'],
            dec_min=row['dec_min'],
            dec_max=row['dec_max'],
            ra_size=row['ra_size'],
            dec_size=row['dec_size'],
            release=release
        )
        mosaics.append(mosaic)
    return mosaics


def get_mosaic_by_field_name(field_name: str, mosaic_coverage_file: str = 'default', release: str = "DR2") -> "Mosaic":
    """
    Get a Mosaic object by its field name.

    :param field_name: Name of the mosaic field
    :param mosaic_coverage_file: Path to the mosaic coverage CSV file
    :param release: Data release ("DR2" or "DR3")
    :return: Mosaic object with the given field name
    """
    mosaic_coverage_file = _get_mosaic_coverage_filepath(mosaic_coverage_file, release)
    from .mosaic import Mosaic

    df = pd.read_csv(mosaic_coverage_file)

    # Find the row with the given field name
    row = df[df['field_name'] == field_name]
    if row.empty:
        raise ValueError(f"Mosaic with field name {field_name} not found in coverage file.")
    row = row.iloc[0]
    mosaic = Mosaic(
        field_name=row['field_name'],
        ra=row['ra'],
        dec=row['dec'],
        ra_min=row['ra_min'],
        ra_max=row['ra_max'],
        dec_min=row['dec_min'],
        dec_max=row['dec_max'],
        ra_size=row['ra_size'],
        dec_size=row['dec_size'],
        release=release
    )
    return mosaic


def _get_mosaic_coverage_filepath(mosaic_coverage_file: str = 'default', release: str = "DR2") -> str:
    """
    Get the file path for the mosaic coverage CSV file. If 'default' is provided, it will look for the default
    coverage file in the data/mosaic_coverage directory of this package.
    
    :param mosaic_coverage_file: Path to the mosaic coverage CSV file or 'default' to use the default file
    :type mosaic_coverage_file: str
    :param release: Data release ("DR2" or "DR3")
    :type release: str
    :return: File path to the mosaic coverage CSV file
    :rtype: str
    """
    if mosaic_coverage_file == 'default':
        if release.upper() == "DR2":
            coverage_file = 'lotss_dr2_mosaic_coverage.csv'
        elif release.upper() == "DR3":
            coverage_file = 'lotss_dr3_mosaic_coverage.csv'
        else:
            raise ValueError(
                f"Unsupported release: {release}, expected 'DR2' or 'DR3'.")
        mosaic_coverage_file = os.path.join(
            PATH_TO_PACKAGE,
            'data',
            'mosaic_coverage',
            coverage_file
        )
    else:
        print(f"Using custom mosaic coverage file: {mosaic_coverage_file}.")
    
    return mosaic_coverage_file


def find_empty_regions(
    mosaic: "Mosaic",
        pybdsf_catalog: pd.DataFrame,
        ra_key: str,
        dec_key: str,
        size_arcmin: float = None,
        size_pixels: int = None,
        max_sources: int = 3,
        grid_step_arcmin: float = None,
        grid_step_pixels: int = None,
        min_separation_arcmin: float = None
    ) -> pd.DataFrame:
    """
    Find empty regions in the mosaic with few or no sources from the catalog.
    
    :param pybdsf_catalog: DataFrame containing the PyBDSF catalog
    :param ra_key: Column name for RA in the catalog
    :param dec_key: Column name for Dec in the catalog
    :param size_arcmin: Size of the region to check in arcminutes
    :param size_pixels: Size of the region to check in pixels
    :param max_sources: Maximum number of sources allowed in an "empty" region (default: 0)
    :param grid_step_arcmin: Step size for grid search in arcminutes (default: size_arcmin/2)
    :param grid_step_pixels: Step size for grid search in pixels (default: size_pixels/2)
    :param min_separation_arcmin: Minimum separation between empty regions (default: size_arcmin)
    :return: DataFrame with columns: ra, dec, num_sources
    """
    if size_arcmin is None and size_pixels is None:
        raise ValueError("Either size_arcmin or size_pixels must be provided.")
    if size_pixels is None:
        size_pixels = arcmin_2_pixel_size(size_arcmin, mosaic.header)
    if size_arcmin is None:
        size_arcmin = pixel_2_arcmin_size(size_pixels, mosaic.header)
    
    # Set default grid step to half the region size
    if grid_step_arcmin is None and grid_step_pixels is None:
        grid_step_arcmin = size_arcmin / 2
    if grid_step_pixels is None:
        grid_step_pixels = arcmin_2_pixel_size(grid_step_arcmin, mosaic.header)
    if grid_step_arcmin is None:
        grid_step_arcmin = pixel_2_arcmin_size(grid_step_pixels, mosaic.header)
    
    # Set default minimum separation
    if min_separation_arcmin is None:
        min_separation_arcmin = size_arcmin

    # Convert catalog to SkyCoord
    catalog_coords = SkyCoord(
        ra=pybdsf_catalog[ra_key].values * u.deg,
        dec=pybdsf_catalog[dec_key].values * u.deg
    )

    # Create a WCS object for coordinate transformations
    wcs = WCS(mosaic.header)
    
    # Calculate search radius (half diagonal of the box)
    search_radius_arcmin = size_arcmin * np.sqrt(2) / 2
    search_radius = search_radius_arcmin * u.arcmin

    # Create grid of test positions
    ra_grid = np.arange(mosaic.ra_min, mosaic.ra_max, grid_step_arcmin / 60)
    dec_grid = np.arange(mosaic.dec_min, mosaic.dec_max, grid_step_arcmin / 60)
    
    empty_regions = []
    
    for ra in tqdm(ra_grid, desc="Scanning RA-DEC grid"):
        for dec in dec_grid:
            # Check if the center is within valid data region
            center = SkyCoord(ra=ra * u.deg, dec=dec * u.deg)
            separation_from_mosaic_center = center.separation(
                SkyCoord(ra=mosaic.ra * u.deg, dec=mosaic.dec * u.deg)
            )
            
            if separation_from_mosaic_center.deg > mosaic.valid_data_radius_deg:
                continue
            
            # Find sources within the search radius
            separations = center.separation(catalog_coords)
            sources_in_region = np.sum(separations < search_radius)
            
            # If region is empty enough, add it to the list
            if sources_in_region <= max_sources:
                empty_regions.append({
                    'ra': ra,
                    'dec': dec,
                    'num_sources': sources_in_region
                })
    
    # Convert to DataFrame
    empty_regions_df = pd.DataFrame(empty_regions)
    
    if len(empty_regions_df) == 0:
        return empty_regions_df
    
    # Filter out regions that are too close to each other
    # Keep the ones with fewer sources
    empty_regions_df = empty_regions_df.sort_values('num_sources')
    filtered_regions = []
    
    for _, row in tqdm(empty_regions_df.iterrows(), total=len(empty_regions_df), desc="Filtering close regions"):
        current_coord = SkyCoord(ra=row['ra'] * u.deg, dec=row['dec'] * u.deg)
        
        # Check if this region is far enough from already selected regions
        too_close = False
        for selected in filtered_regions:
            selected_coord = SkyCoord(ra=selected['ra'] * u.deg, dec=selected['dec'] * u.deg)
            if current_coord.separation(selected_coord).arcmin < min_separation_arcmin:
                too_close = True
                break
        
        if not too_close:
            filtered_regions.append(row.to_dict())
    
    return pd.DataFrame(filtered_regions)